n = input('digite algo:')
print(type(n))
print('É letra?', (n.isalpha()))
print('É número?', (n.isnumeric()))
print('É decimal?', (n.isdecimal()))
print('É alfanúmerico?', (n.isalnum()))
print('Só Tem espaços?', (n.isspace()))
print('É só maiúsculo?', (n.isupper()))
print('Esta em minúscula?', (n.islower()))
print('Esta capitalizada?', (n.istitle()))
